/**
 * Created by Jojo on 13.05.17.
 */

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

public class GUI extends javax.swing.JFrame {

    private Table first;
    private Table second;



    private Table third;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

        first = new Table(new String[]{"Ankunftszeit Gruppen", "Einstiegszeit","Fahrtzeit","Ausstiegszeit","Zustand Zug", "Aktueller Wagon", "Freie Plätze Wagon", "Länge Warte M", "Länge Warte S","SimZeit", "Fährgäste", "Zugfahrten"});
        second = new Table(new String[]{"Gruppengröße", "Ankunftzeit","Einteilungszeit","Ausstiegszeit"});
        third = new Table(new String[]{"Beförderte Fahrgäste", "Zugfahrten", "MaxAuslastung", "Auslastungsqoute","Durchschnittliche Wartezeit"});
        p_first.add(first);
        p_second.add(second);
        p_third.add(third);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        p_center = new javax.swing.JPanel();
        p_first = new javax.swing.JPanel();
        p_second = new javax.swing.JPanel();
        p_third = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_center.setLayout(new java.awt.GridLayout(3, 0));

        p_first.setLayout(new java.awt.BorderLayout());
        p_center.add(p_first);

        p_second.setLayout(new java.awt.BorderLayout());
        p_center.add(p_second);

        p_third.setLayout(new java.awt.BorderLayout());
        p_center.add(p_third);

        getContentPane().add(p_center, java.awt.BorderLayout.CENTER);

        jButton1.setText("Add Column");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        first.addColumn(new String[]{"1","2","3"});
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel p_center;
    private javax.swing.JPanel p_first;
    private javax.swing.JPanel p_second;
    private javax.swing.JPanel p_third;
    // End of variables declaration


    public Table getFirst() {
        return first;
    }

    public Table getSecond() {
        return second;
    }

    public Table getThird() {
        return third;
    }
}
